### ISSUE TITLE
Uploaded CSS and Missing Images

### ISSUE THREAD

**Issue by enorthrup** [CIDI/kennethware-2.0#30]
Hi Kenneth,

I noticed when testing the September 21 2015 version of Kennethware with the new UI in Canvas that the banner.png, bookmark.png, and divider.png  (originally located in canvasImages) aren’t picked up.  They are supposed to be moved to a folder called images in the same location as the CSS, but since the CSS is now uploaded for the new UI, the relative addressing used to access these images no longer works.

Elena

**Comment by duniken** [comment]
Elena, thanks for pointing this out. As I see it, there are 2 options you can take:

1. I believe that you should be able to zip the css and images and upload the zipped file to Canvas (see https://community.canvaslms.com/docs/DOC-4355)
2. Find a server where you can host the images and change the css to a full url instead of a relative url.

I will add a note to the installation instructions indicating these options.

**Comment by enorthrup** [comment]
Hi Kenneth,

Thanks for the quick reply.  I was trying to make as few changes to your code as possible.  Thanks very much for the tip on the zip files.  I’ll try that approach.

Elena
